// =============================================================================
// BLOG INDEX
// Auto-generated by the Empire-HQ n8n publisher.
// =============================================================================

const posts = [
] as Array<{ t: string; s: string; e: string; d: string; r: string; tg: string[] }>

export default posts
